"""empty message

Revision ID: 30db50260672
Revises: 6f37969fd739
Create Date: 2018-01-02 20:35:53.225652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30db50260672'
down_revision = '6f37969fd739'
branch_labels = None
depends_on = None


def upgrade():
	op.drop_table('spots')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spots',
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    # sa.Column('loc_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['id'], ['locations.id'], )
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spots')
    # ### end Alembic commands ###
