"""empty message

Revision ID: 7f1f88f65565
Revises: cd2e051367c9
Create Date: 2018-01-02 21:21:37.211665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1f88f65565'
down_revision = 'cd2e051367c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loc_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spots')
    # ### end Alembic commands ###
